### ISSUE TITLE
your indexed records for Mark Olivier. 2018. Melandrena associated pollinator Callophrys niphon. iNaturalist.org. Accessed at <https://www.inaturalist.org/observations/17912899> on 06 Jul 2022.

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/inaturalist#4]
Hi!

Thanks for helping to make existing biotic interaction data easier to find and access!

I was just looking at your GloBI indexed record at https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Callophrys%20niphon&targetTaxon=Melandrena and I was wondering about ... (please add your own text)

I am seeing that Associated Pollinator on iNaturalist means that it is another pollinator visiting the same flower, but it looks like it is being interpreted as the interaction _pollinates_. I would expect that the interaction should be _interacts with_

![Screen Shot 2022-07-08 at 1 34 07 PM](https://user-images.githubusercontent.com/1044474/178066553-09145eb0-9a91-4108-8db7-99616b9de1e3.png)

Thank you!

**Comment by jhpoelen** [comment]
@seltmann thanks for suggesting that associated pollinator should be mapped to interacts with, instead of pollinates. I've applied the change as suggested. 

I left a comment related to https://www.inaturalist.org/observations/17912899, see https://www.inaturalist.org/observations/17912899#activity_comment_ca6f9d38-200b-4fb4-8339-503b2fc1a410 . 

![image](https://user-images.githubusercontent.com/1084872/218145093-a9e94be7-c4bf-48ba-ab65-36ac85cd3afc.png)
